# Generated by Django 5.1.1 on 2024-09-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('made_in', models.CharField(max_length=100)),
                ('made_year', models.DateField()),
                ('product_color', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='products_image')),
            ],
        ),
    ]
